######################################################################
# Automatically generated by qmake (2.01a) Sat Jul 17 11:57:40 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Fenetre.h
SOURCES += Fenetre.cpp safe.cpp
